spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true

#logging.level.it.accenture=DEBUG
#logging.level.dev.langchain4j=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.boot.autoconfigure=INFO
#
##langchain4j.anthropic.chat-model.base-url=https://sol.massimilianopili.com/proxy/ai/generic/v1/
##langchain4j.anthropic.chat-model.api-key=claude_client
##langchain4j.anthropic.chat-model.model-name=claude-haiku-4-5-20251001
##langchain4j.anthropic.chat-model.max-tokens=200
#
#langchain4j.open-ai.chat-model.api-key=${NVIDIA_API_KEY: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}
#langchain4j.open-ai.chat-model.base-url=https://integrate.api.nvidia.com/v1
#langchain4j.open-ai.chat-model.model-name=mistralai/ministral-14b-instruct-2512
#langchain4j.open-ai.chat-model.max-tokens=200
